#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2019 Firejail Authors
# License GPL v2

set timeout 30
spawn $env(SHELL)
match_max 100000

send -- "firejail --trace mkdir ttt\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"mkdir:mkdir ttt"
}
sleep 1

send -- "firejail --trace rmdir ttt\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"rmdir:rmdir ttt"
}
sleep 1

send -- "firejail --trace touch ttt\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"touch:open ttt" {puts "OK\n";}
	"touch:open64 ttt" {puts "OK\n";}
}
sleep 1

send -- "firejail --trace rm ttt\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"rm:unlinkat ttt"
}
sleep 1

send --  "firejail --trace\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"bash:open /dev/tty" {puts "64bit\n"}
	"bash:open64 /dev/tty" {puts "32bit\n"}
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"bash:access /etc/terminfo/" {puts "debian\n"}
	"bash:access /usr/share/terminfo/" {puts "arch\n"}
}
after 100

puts "\nall done\n"
